# Documentation: https://gohugo.io/configuration/build/#cache-busters

[buildStats]
enable = true

[[cachebusters]]
source = 'assets/watching/hugo_stats\.json'
target = 'main\.(css|styles|scss|sass)'
[[cachebusters]]
source = '(postcss|tailwind)\.config\.js'
target = 'css'
[[cachebusters]]
source = 'layouts/.*'
target = 'css'
