# Documentation: https://gohugo.io/configuration/caches/

[assets]
dir = ':resourceDir/_gen'
maxAge = -1
[images]
dir = ':resourceDir/_gen'
maxAge = -1
[getresource]
dir = ':cacheDir/:project'
maxAge = 0
[misc]
dir = ':cacheDir/:project'
maxAge = 0
[modulegitinfo]
dir = ':cacheDir/modules'
maxAge = '24h'
[modulequeries]
dir = ':cacheDir/modules'
maxAge = '24h'
[modules]
dir = ':cacheDir/modules'
maxAge = 0
