# Documentation:
# https://gohugo.io/configuration/languages/#language-settings
# https://gohugo.io/configuration/markup/#table-of-contents

[goldmark]
[goldmark.extensions]
strikethrough = true

[goldmark.parser]
wrapStandAloneImageWithinParagraph = false

[goldmark.parser.attribute]
title = true
block = true

[goldmark.extensions.extras]
[goldmark.extensions.extras.delete]
enable = false
[goldmark.extensions.extras.insert]
enable = false
[goldmark.extensions.extras.mark]
enable = true
# To avoid a conflict, if you enable the “subscript” feature of the Extras extension, you must disable the Strikethrough extension.
[goldmark.extensions.extras.subscript]
enable = false
[goldmark.extensions.extras.superscript]
enable = true

[goldmark.renderer]
unsafe = true

[tableOfContents]
endLevel = 3
ordered = true
startLevel = 2
