# Documentation:
# https://gohugo.io/configuration/introduction/#configuration-directory
# https://gohugo.io/configuration/module/#mounts

[hugoVersion]
extended = true
min = "0.149.0"
max = "0.149.0"

[[mounts]]
source = 'assets'
target = 'assets'
[[mounts]]
source = 'content'
target = 'content'
[[mounts]]
source = 'data'
target = 'data'
[[mounts]]
source = 'i18n'
target = 'i18n'
[[mounts]]
source = 'layouts'
target = 'layouts'
[[mounts]]
source = 'static'
target = 'static'
[[mounts]]
source = 'hugo_stats.json'
target = 'assets/watching/hugo_stats.json'
[[mounts]]
source = "node_modules/bootstrap/scss"
target = "assets/sass/vendors/bootstrap"
[[mounts]]
source = "node_modules/bootstrap/dist/js"
target = "assets/js/vendors/bootstrap"
[[mounts]]
source = "node_modules/@fortawesome/fontawesome-free/scss"
target = "assets/sass/vendors/fontawesome"
[[mounts]]
source = "node_modules/@fortawesome/fontawesome-free/webfonts"
target = "static/webfonts"
