baseURL = 'https://schitul-mironesti.ro'
languageCode = 'ro'
defaultcontentlanguage = "ro"
title = 'Schitul Mironești'
theme = 'schitul-mironesti'
disableKinds = ["taxonomy", "taxonomyTerm"]
disableHugoGeneratorInject = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  author = "Schitul Mironești"
  description = "Biserica Sf. Ierarh Nicolae din Mironești, se află la sud de râul Argeș, în apropierea Mânăstirii Comana."
  keywords = ["Schitul Mironesti"]
  favicon = "favicon/favicon.ico"
  googleMapsLink = ""
  googleTagManager = ""
  robotsActive = "index, follow"
  googleBotActive = "index,follow,snippet,archive"
  BotsInactive = "noindex, nofollow"
  themeColorLight = "#000"
  themeColorDark = "#fff"

[params.footer]
  [params.footer.info]
  heading = "Investim în viitorul tău! Proiect cofinanțat din Fondul European de Dezvoltare Regională prin Programul Operațional Regional 2014-2020"
  text = "Conținutul acestui material nu reprezintă în mod obligatoriu poziția oficială a Uniunii Europene sau a Guvernului României"
  
  [[params.footer.links]]
    title = "www.inforegio.ro"
    url = "https://www.inforegio.ro"

  [[params.footer.links]]
    title = "facebook.com/inforegio.ro"
    url = "https://facebook.com/inforegio.ro"

  [params.footer.contactInfo]
    address = "Strada Principală, Mironeşti"
    city = "Giurgiu"
    phone = ""
    fax = ""
    person = ""
    copyright = "2023 Schitul Mironești"

[menu]
  # Main Menu
  [[menu.main]]
    name = "Acasă"
    url = "/"
    weight = 10

  [[menu.main]]
    name = "Istoric"
    url = "/istoric/"
    weight = 20

  [[menu.main]]
    name = "Proiect SMIS 126844"
    url = "/proiect-smis-126844/"
    weight = 30

  [[menu.main]]
    name = "Digitalizare 3D"
    url = "/digitalizare-3d/"
    weight = 40

  [[menu.main]]
    name = "Galerie"
    url = "/galerie/"
    weight = 50

  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 60
