# Documentation: https://gohugo.io/configuration/menus/

# Main Menu
[[main]]
name        = "Acasă"
url         = "/"
pre         = ""
post        = ""
title       = "Acasă"
parent      = ""
pageRef     = ""
identifier  = ""
weight      = 10

[[main]]
name        = "Istoric"
url         = ""
pre         = ""
post        = ""
title       = "Istoric"
parent      = ""
pageRef     = "history"
identifier  = ""
weight      = 20

[[main]]
name        = "Proiect SMIS 126844"
url         = ""
pre         = ""
post        = ""
title       = "Proiect SMIS 126844"
parent      = ""
pageRef     = "project-1"
identifier  = ""
weight      = 30

[[main]]
name        = "Digitizare 3D"
url         = ""
pre         = ""
post        = ""
title       = "Digitizare 3D"
parent      = ""
pageRef     = "digitisation"
identifier  = ""
weight      = 40

[[main]]
name        = "Galerie"
url         = ""
pre         = ""
post        = ""
title       = "Galerie"
parent      = ""
pageRef     = "gallery"
identifier  = ""
weight      = 50

[[main]]
name        = "Contact"
url         = ""
pre         = ""
post        = ""
title       = "Contact"
parent      = ""
pageRef     = "contact"
identifier  = ""
weight      = 60
